// Sample actions
export const ADD_ALL_DINING_RESTAURANTS = "ADD_ALL_DINING_RESTAURANTS"
export const ADD_ALL_DELIVERY_RESTAURANTS = "ADD_ALL_DELIVERY_RESTAURANTS"
export const SELECT_RESTAUARANT = "SELECT_RESTAUARANT"
export const ADD_USER_DATA = "ADD_USER_DATA"

export const LOGOUT = "LOGOUT"
