// Sample actions
export const ADD_CURRENT_WEATHER_DATA = "ADD_CURRENT_WEATHER_DATA"
export const ADD_ALL_DINING_RESTAURANTS = "ADD_ALL_DINING_RESTAURANTS"
export const ADD_ALL_DELIVERY_RESTAURANTS = "ADD_ALL_DELIVERY_RESTAURANTS"
export const SELECT_RESTAUARANT = "SELECT_RESTAUARANT"